name: Deploy Next.js to GitHub Pages 🚀
run-name: ${{ github.actor }} is testing out Gitea Actions

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build static site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch the output should be pushed to
          folder: out       # The folder that contains the static site files
          token: ${{ secrets.GH_TOKEN }}
